baseURL = 'https://blog.domin.network/'
languageCode = 'en-us'
theme = 'JuiceBar'
title = 'Domin Network'

[params]
author = 'Domin OIG'

[[params.social]]
name = 'twitter'
url = 'https://twitter.com/domin_network'

[[params.social]]
name = 'github'
url = 'https://github.com/Domin-Network'

[[params.social]]
name = 'email'
url = 'mailto:contact@redreamer.io'

[module]
[module.hugoVersion]
min = "0.75.0"
