baseURL = 'https://blog.domin.network/'
languageCode = 'en-us'
theme = 'JuiceBar'
title = 'Domin Network'

[params]
author = 'Domin OIG'

[[params.social]]
name = 'twitter'
url = 'https://twitter.com/domin_network'

[[params.social]]
name = 'github'
url = 'https://github.com/Domin-Network'

[[params.social]]
name = 'email'
url = 'mailto:contact@redreamer.io'

[[menu.main]]
name = 'Home'
url = '/'

[[menu.main]]
name = 'About'
url = '/about/'
