baseURL = 'https://blog.domin.network/'
languageCode = 'en-us'
title = 'Domin Network'
theme = "JuiceBar"

[params]
author = "Domin Network"
github = "domin-network"
url = "https://www.domin.network"
keywords = "Domin Network, Blockchain, Web3, Open data"

[[params.social]]
name = 'twitter'
url = 'https://twitter.com/domin_network'

[[params.social]]
name = 'github'
url = 'https://github.com/Domin-Network'

[[params.social]]
name = 'email'
url = 'mailto:contact@redreamer.io'

[[menu.main]]
name = 'Home'
url = '/'

[[menu.main]]
name = 'About'
url = '/about/'
